g29_feedback_publisher:
  ros__parameters:
    device_name: "/dev/input/event19"
    loop_period: 0.1
    pub_period: 0.25
    max_torque: 1.0
    min_torque: 0.2
    brake_torque: 0.2
    brake_position: 0.1
    auto_centering_max_torque: 0.2
    auto_centering_max_position: 0.1
    eps: 0.05
    auto_centering: true
